#pragma once
#include <GLFW/glfw3.h>

namespace nebula {

enum class Key : int {
    A=GLFW_KEY_A, B=GLFW_KEY_B, C=GLFW_KEY_C, D=GLFW_KEY_D,
    E=GLFW_KEY_E, F=GLFW_KEY_F, G=GLFW_KEY_G, H=GLFW_KEY_H,
    I=GLFW_KEY_I, J=GLFW_KEY_J, K=GLFW_KEY_K, L=GLFW_KEY_L,
    M=GLFW_KEY_M, N=GLFW_KEY_N, O=GLFW_KEY_O, P=GLFW_KEY_P,
    Q=GLFW_KEY_Q, R=GLFW_KEY_R, S=GLFW_KEY_S, T=GLFW_KEY_T,
    U=GLFW_KEY_U, V=GLFW_KEY_V, W=GLFW_KEY_W, X=GLFW_KEY_X,
    Y=GLFW_KEY_Y, Z=GLFW_KEY_Z,
    Num0=GLFW_KEY_0, Num1=GLFW_KEY_1, Num2=GLFW_KEY_2,
    Num3=GLFW_KEY_3, Num4=GLFW_KEY_4, Num5=GLFW_KEY_5,
    Num6=GLFW_KEY_6, Num7=GLFW_KEY_7, Num8=GLFW_KEY_8, Num9=GLFW_KEY_9,
    Space=GLFW_KEY_SPACE, Enter=GLFW_KEY_ENTER, Escape=GLFW_KEY_ESCAPE,
    Tab=GLFW_KEY_TAB,     Backspace=GLFW_KEY_BACKSPACE,
    Left=GLFW_KEY_LEFT,   Right=GLFW_KEY_RIGHT,
    Up=GLFW_KEY_UP,       Down=GLFW_KEY_DOWN,
    LShift=GLFW_KEY_LEFT_SHIFT,   RShift=GLFW_KEY_RIGHT_SHIFT,
    LCtrl=GLFW_KEY_LEFT_CONTROL,  RCtrl=GLFW_KEY_RIGHT_CONTROL,
    F1=GLFW_KEY_F1, F2=GLFW_KEY_F2, F3=GLFW_KEY_F3,
    F4=GLFW_KEY_F4, F5=GLFW_KEY_F5, F6=GLFW_KEY_F6,
};

enum class MouseButton : int {
    Left  = GLFW_MOUSE_BUTTON_LEFT,
    Right = GLFW_MOUSE_BUTTON_RIGHT,
    Middle= GLFW_MOUSE_BUTTON_MIDDLE,
};

} // namespace nebula